"""Renders ``pi_capture/_attributes.py`` from the frozen requirements spec.

The spec (``packages/pi_capture/spec/requirements_v2_attributes.json``) is the owner's list of
143 attributes plus two ruled local additions (145; see ``spec/README.md``). This module turns
it into Python source: four ``StrEnum`` classes whose members are exactly the distinct values found
in the data, the frozen ``Attribute`` record, and the ``ATTRIBUTES`` tuple. The rendered text is
checked in; ``tests/test_registry.py`` renders it again and compares, so the module can never
drift from the spec unnoticed.

``scripts/gen_registry.py`` is the command-line wrapper.
"""

from __future__ import annotations

import json
import re
from collections.abc import Iterable, Mapping, Sequence
from pathlib import Path
from typing import Any

SPEC_DIR = Path(__file__).resolve().parents[2] / "spec"
SPEC_PATH = SPEC_DIR / "requirements_v2_attributes.json"
TARGET_PATH = Path(__file__).resolve().with_name("_attributes.py")

# The spec's short keys and the record fields they become.
REQUIRED_SPEC_KEYS = ("k", "g", "lvl", "v", "t", "ex", "req", "src")
OPTIONAL_SPEC_KEYS = ("note", "detail_only")

_HEADER = '''# ruff: noqa: E501
"""GENERATED by scripts/gen_registry.py from spec/requirements_v2_attributes.json. Do not edit.

The requirement attributes (requirements v2, artifact 01a0fc4d-c4b7-7f41-a3aa-65ae1ae534d8) as
frozen records. Enum members are the distinct values present in the spec, nothing more.
``tests/test_registry.py`` re-renders this module from the spec and fails on any difference.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum

'''

_RECORD = '''

@dataclass(frozen=True, slots=True)
class Attribute:
    """One registered attribute: its key, where it belongs and what the spec says about it."""

    key: str
    group: AttributeGroup
    level: AttributeLevel
    verticals: tuple[Vertical, ...]
    type: str
    source: AttributeSource
    requirement: str
    detail_only: bool
    example: str
    note: str | None

'''


class SpecError(ValueError):
    """The spec file does not have the expected shape."""


def load_spec(path: Path = SPEC_PATH) -> list[dict[str, Any]]:
    """Read and validate the attribute list: a JSON array of objects with the known keys."""
    raw = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(raw, list) or not raw:
        raise SpecError("spec must be a non-empty JSON array")
    allowed = set(REQUIRED_SPEC_KEYS) | set(OPTIONAL_SPEC_KEYS)
    seen: set[str] = set()
    for i, item in enumerate(raw):
        if not isinstance(item, dict):
            raise SpecError(f"attribute #{i} is not an object")
        missing = [k for k in REQUIRED_SPEC_KEYS if k not in item]
        unknown = sorted(set(item) - allowed)
        if missing or unknown:
            raise SpecError(
                f"attribute #{i} ({item.get('k')!r}): missing {missing}, unknown {unknown}"
            )
        _check_item(i, item)
        if item["k"] in seen:
            raise SpecError(f"duplicate attribute key {item['k']!r}")
        seen.add(item["k"])
    return raw


def _check_item(i: int, item: Mapping[str, Any]) -> None:
    for key in ("k", "g", "lvl", "t", "ex", "req", "src"):
        if not isinstance(item[key], str) or not item[key]:
            raise SpecError(f"attribute #{i}: {key!r} must be a non-empty string")
    verticals = item["v"]
    if (
        not isinstance(verticals, list)
        or not verticals
        or not all(isinstance(v, str) and v for v in verticals)
    ):
        raise SpecError(f"attribute #{i} ({item['k']!r}): 'v' must list at least one vertical")
    if item.get("note") is not None and not isinstance(item["note"], str):
        raise SpecError(f"attribute #{i} ({item['k']!r}): 'note' must be a string or null")
    if item.get("detail_only") not in (None, True, False):
        raise SpecError(
            f"attribute #{i} ({item['k']!r}): 'detail_only' must be true, false or null"
        )


_IDENT_RE = re.compile(r"[^0-9a-zA-Z]+")


def member_name(value: str) -> str:
    """``page or feed`` -> ``PAGE_OR_FEED``; ``page, mapped`` -> ``PAGE_MAPPED``."""
    name = _IDENT_RE.sub("_", value).strip("_").upper()
    if not name or name[0].isdigit():
        raise SpecError(f"cannot derive an enum member name from {value!r}")
    return name


def distinct(values: Iterable[str]) -> list[str]:
    """Distinct values in first-seen order (the spec's own order, not alphabetical)."""
    return list(dict.fromkeys(values))


def literal(value: str | None) -> str:
    """A Python string literal the way ``ruff format`` writes it: double quotes unless the text
    holds more double than single quotes; backslashes, quotes and line breaks escaped."""
    if value is None:
        return "None"
    quote = "'" if value.count('"') > value.count("'") else '"'
    body = (
        value.replace("\\", "\\\\")
        .replace(quote, "\\" + quote)
        .replace("\n", "\\n")
        .replace("\r", "\\r")
        .replace("\t", "\\t")
    )
    return f"{quote}{body}{quote}"


def _render_enum(name: str, doc: str, values: Sequence[str]) -> str:
    lines = [f"class {name}(StrEnum):", f'    """{doc}"""', ""]
    lines += [f"    {member_name(v)} = {literal(v)}" for v in values]
    return "\n".join(lines) + "\n"


def _render_attribute(item: Mapping[str, Any]) -> str:
    members = [f"Vertical.{member_name(v)}" for v in item["v"]]
    # ruff keeps a multi-element tuple with a trailing comma expanded, but collapses a
    # one-element tuple (its comma is syntax, not a magic trailing comma).
    if len(members) == 1:
        verticals_src = f"verticals=({members[0]},)"
    else:
        verticals = "".join(f"            {m},\n" for m in members)
        verticals_src = f"verticals=(\n{verticals}        )"
    fields = [
        f"key={literal(item['k'])}",
        f"group=AttributeGroup.{member_name(item['g'])}",
        f"level=AttributeLevel.{member_name(item['lvl'])}",
        verticals_src,
        f"type={literal(item['t'])}",
        f"source=AttributeSource.{member_name(item['src'])}",
        f"requirement={literal(item['req'])}",
        f"detail_only={bool(item.get('detail_only'))!r}",
        f"example={literal(item['ex'])}",
        f"note={literal(item.get('note'))}",
    ]
    body = "".join(f"        {f},\n" for f in fields)
    return f"    Attribute(\n{body}    ),\n"


def render(spec: Sequence[Mapping[str, Any]]) -> str:
    """The full text of ``_attributes.py`` for this spec."""
    groups = distinct(item["g"] for item in spec)
    lvls = distinct(item["lvl"] for item in spec)
    verticals = distinct(v for item in spec for v in item["v"])
    srcs = distinct(item["src"] for item in spec)
    enums = "\n\n".join(
        [
            _render_enum("AttributeGroup", "Spec attribute group (``g``).", groups),
            _render_enum(
                "AttributeLevel", "Product level the attribute belongs to (``lvl``).", lvls
            ),
            _render_enum("Vertical", "Vertical an attribute applies to (``v``).", verticals),
            _render_enum(
                "AttributeSource", "Where the spec says a value comes from (``src``).", srcs
            ),
        ]
    )
    rows = "".join(_render_attribute(item) for item in spec)
    return f"{_HEADER}\n{enums}{_RECORD}\nATTRIBUTES: tuple[Attribute, ...] = (\n{rows})\n"


def write(spec_path: Path = SPEC_PATH, target: Path = TARGET_PATH) -> Path:
    target.write_text(render(load_spec(spec_path)), encoding="utf-8")
    return target
