// Types of the read API, derived from the committed contract (docs/contracts/pi-api.openapi.json).
// schema.gen.ts is generated by `npm run gen:api`; CI fails if it drifts from the contract.
import type { components, paths } from './schema.gen';

export type Schemas = components['schemas'];
export type Money = Schemas['MoneyValue'];
export type Localized = Schemas['Localized'];
export type Reason = Schemas['Reason'];
export type CaveatView = Schemas['CaveatView'];
export type ApiMeta = Schemas['ApiMeta'];
export type ErrorBody = Schemas['ErrorBody'];

/** Every 200 body shares this shape: `data` is null (or partial) when `status` is not_enough_data. */
export interface Envelope<T> {
  status: Schemas['Status'];
  data: T | null;
  meta: ApiMeta;
  caveats: CaveatView[];
  cohort?: Schemas['Cohort'] | null;
  reason?: Reason | null;
  detail?: Localized | null;
}

/** Routes that answer GET. */
export type GetPath = { [P in keyof paths]: paths[P] extends { get: object } ? P : never }[keyof paths];
type GetOp<P extends GetPath> = paths[P] extends { get: infer O } ? O : never;

export type QueryOf<P extends GetPath> =
  GetOp<P> extends { parameters: { query?: infer Q } } ? NonNullable<Q> : never;
export type PathParamsOf<P extends GetPath> =
  GetOp<P> extends { parameters: { path: infer X } } ? (X extends Record<string, string> ? X : never) : never;
export type ResponseOf<P extends GetPath> =
  GetOp<P> extends { responses: { 200: { content: { 'application/json': infer R } } } } ? R : never;

/** Error codes the API sends in `error.code` (pi_api). Anything else is treated as `unexpected`. */
export const API_ERROR_CODES = [
  'unauthenticated',
  'forbidden',
  'not_found',
  'stale_cursor',
  'invalid_request',
  'invalid_query',
  'ambiguous_dataset',
  'rate_limited',
  'data_unavailable',
  'auth_unavailable',
  'internal_error',
] as const;
export type ApiErrorCode = (typeof API_ERROR_CODES)[number] | 'network' | 'unexpected';
