"""Render ``docs/requirements/uat_status.md`` from the register and the UAT cases.

Regenerate with ``make uat-status``; ``test_traceability.py`` fails when the
checked-in file is stale.
"""

from __future__ import annotations

import argparse
import sys
from collections import Counter

from uat.registry import (
    MILESTONES,
    STATUS_MD,
    Requirement,
    UatCase,
    discover_cases,
    load_requirements,
)


def _cell(text: str) -> str:
    return text.replace("|", "\\|")


def render(reqs: dict[str, Requirement], cases: list[UatCase]) -> str:
    by_req: dict[str, list[UatCase]] = {}
    for case in cases:
        by_req.setdefault(case.req_id, []).append(case)
    pilot = [r for r in reqs.values() if r.in_pilot]

    def status(req: Requirement) -> str:
        own = by_req.get(req.id, [])
        if not own:
            return "missing"
        return "implemented" if all(c.implemented for c in own) else "pending"

    lines = [
        "# UAT status",
        "",
        "<!-- Generated by `make uat-status` (tests/uat/report.py). Do not edit by hand. -->",
        "",
        "Pilot-scope requirements from `docs/requirements/traceability.csv` mapped to UAT",
        "cases in `tests/uat/cases`. A requirement is *implemented* when all of its cases",
        "are; *pending* cases are strict xfails until their milestone lands.",
        "",
        "## Summary",
        "",
        "| Milestone | Cases | Implemented | Pending |",
        "|---|---:|---:|---:|",
    ]
    for ms in MILESTONES:
        own = [c for c in cases if c.milestone == ms]
        done = sum(c.implemented for c in own)
        lines.append(f"| {ms.upper()} | {len(own)} | {done} | {len(own) - done} |")
    done_total = sum(c.implemented for c in cases)
    lines.append(
        f"| **Total** | **{len(cases)}** | **{done_total}** | **{len(cases) - done_total}** |"
    )
    counts = Counter(status(r) for r in pilot)
    lines += [
        "",
        f"Pilot-scope requirements: **{len(pilot)}** — implemented {counts['implemented']}, "
        f"pending {counts['pending']}, missing {counts['missing']}.",
        "",
        "## Requirements",
        "",
        "| ID | Module | Pri | Gate | Requirement | Milestone | Status | Case |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for req in pilot:
        own = by_req.get(req.id, [])
        milestones = ", ".join(sorted({c.milestone.upper() for c in own})) or "—"
        where = "<br>".join(f"`{c.nodeid}`" for c in own) or "—"
        lines.append(
            f"| {req.id} | {_cell(req.module)} | {req.priority} | {req.gate} "
            f"| {_cell(req.title)} | {milestones} | {status(req)} | {where} |"
        )
    extra = sorted({c.req_id for c in cases if c.req_id in reqs and not reqs[c.req_id].in_pilot})
    if extra:
        lines += [
            "",
            "Cases also exist for non-pilot (later or deviation) requirements: "
            + ", ".join(extra)
            + ".",
        ]
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="exit 1 if the file is stale")
    args = parser.parse_args(argv)
    text = render(load_requirements(), discover_cases())
    if args.check:
        current = STATUS_MD.read_text(encoding="utf-8") if STATUS_MD.exists() else ""
        if current != text:
            print(f"{STATUS_MD} is stale; run `make uat-status`", file=sys.stderr)
            return 1
        return 0
    STATUS_MD.write_text(text, encoding="utf-8")
    print(f"wrote {STATUS_MD}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
